---
title: "exo3_Github"
format: html
editor: visual
---
# ======= TD3 ========

# Question 1
Fallait faire tout le truc sur github, un commit et un push.

# Question 2
```{r}
df_velo <- read.csv("data/velo.csv", sep=";")
```

Deux boucles favorites :
```{r}
df_b_788 <- df_velo[df_velo$Numéro.de.boucle == 788, ]
df_b_673 <- df_velo[df_velo$Numéro.de.boucle == 673, ]
```

Deux jours favoris:
```{r}
df_d_0917 <- df_velo[df_velo$Jour == "2025-09-17", ]
df_d_0928 <- df_velo[df_velo$Jour == "2025-09-28", ]
```


# Question 3
```{r}
filtre_anomalie <- function(df){
  df_filtre <- df[!(df$Probabilité.de.présence.d.anomalies =="Faible"|
                    df$Probabilité.de.présence.d.anomalies =="Forte"),]
    return(df_filtre)
}
```


```{r}
filtre_anomalie(df_d_0917)
filtre_anomalie(df_d_0928)
filtre_anomalie(df_b_788)
filtre_anomalie(df_b_673)
```
# Question 4
```{r}
compter_nombre_trajets <- function(df){
  return(sum(df$Total))
}
```

```{r}
compter_nombre_trajets(df_d_0917)
compter_nombre_trajets(df_d_0928)
compter_nombre_trajets(df_b_788)
compter_nombre_trajets(df_b_673)
```
# Question 5
```{r}
compter_nombre_boucle <- function(df){
  nb_boucle<- length(unique(df$Boucle.de.comptage))
  return(nb_boucle)
}
```

```{r}
compter_nombre_boucle(df_d_0917)
compter_nombre_boucle(df_d_0928)
compter_nombre_boucle(df_b_788)
compter_nombre_boucle(df_b_673)
```
Oui c'était totalement prévisible.

# Question 6
```{r}
trouver_trajet_max <- function(df){
  max <- which.max(df$Total)
  nom <- df$Boucle.de.comptage[max]
  jour <- df$Jour[max]
  nb_passage <-df$Total[max]
  
  resultat <- data.frame(
    nom=nom,
    jour=jour,
    nb_passage=nb_passage)
    
  
  return(resultat)
}
```

```{r}
trouver_trajet_max(df_d_0917)
trouver_trajet_max(df_d_0928)
trouver_trajet_max(df_b_673)
trouver_trajet_max(df_b_788)
```
# Question 7



