---
title: "TD4_github"
format: html
editor: visual
---

PAS A L'EXAMEN !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TROP CHOUETTE C'EST LA FIESTA

# ======= TD4 ========

# === Question 1

```{r}
library(httr2)

req <- request("https://data.nantesmetropole.fr/api/explore/v2.1/catalog/datasets/") |>
    req_url_path_append("244400404_comptages-velo-nantes-metropole-boucles-comptage/records") |>
    req_url_query(limit= 100)

resp <- req_perform(req)  |> resp_body_json(simplifyVector = TRUE)
df_velo_info  <- resp$results
```

# === Question 2

```{r}
req <- request("https://data.nantesmetropole.fr/api/explore/v2.1/catalog/datasets/") |>
    req_url_path_append("244400404_comptages-velo-nantes-metropole/records") |>
    req_url_query(limit= 100, refine = "boucle_num:880", refine = "boucle_num:881", refine = "jour:'2025-05'")

resp <- req_perform(req)  |> resp_body_json(simplifyVector = TRUE)
df_velo_sample  <- resp$results

df_velo_info
```
# === Question 3

```{r}
library(dplyr)

df_velo_final <- df_velo_sample |>
  left_join(df_velo_info, by = "boucle_num")
```

```{r}
write.csv(df_velo_final, "data/df_velo_final.csv", row.names = FALSE)
```
# === Question 4

```{r}
df_velo <- read.delim("data/df_velo_final.csv", sep = ",")
```

Convertir en tibble
```{r}
library(tibble)

df_velo <- as_tibble(df_velo)
```

```{r}
library(dplyr)

df_velo_clean <- df_velo |>
  filter(
    !(probabilite_presence_anomalie %in% c("Fort", "Faible")),
    total >= 0,
    total <= 10000
  )
```

# === Question 5

```{r}
library(dplyr)

df_velo_clean <- df_velo_clean |>
  mutate(
    mois = format(as.Date(jour), "%B")
  )
```


```{r}
trajets_par_mois <- df_velo_clean |>
  group_by(mois) |>
  summarise(
    total_trajets = sum(total, na.rm = TRUE)
  ) |>
  arrange(total_trajets)

trajets_par_mois
```
# === Question 6
```{r}
library(dplyr)
library(tidyr)

df_long <- df_velo_clean |>
  pivot_longer(
    cols = starts_with("X"),
    names_to = "heure",
    values_to = "nb_trajets"
  )
```

```{r}
df_long <- df_long |>
  mutate(
    heure = as.numeric(gsub("X", "", heure))
  )
```

```{r}
trajets_par_heure <- df_long |>
  group_by(heure) |>
  summarise(
    moyenne_trajets = mean(nb_trajets, na.rm = TRUE)
  ) |>
  arrange(desc(moyenne_trajets))

trajets_par_heure
```

# === Question 7
```{r}
library(dplyr)
library(stringr)

df_velo_clean <- df_velo_clean |>
  mutate(
    heure = as.numeric(str_extract(heure, "^\\d{2}"))
  )
```

